import { Injectable } from "@angular/core";
import { InMemoryDbService } from "angular-in-memory-web-api";
import {Book} from "../model/book";

@Injectable({
  providedIn: "root"
})
export class InMemoryDataService implements InMemoryDbService {

  constructor() { }

  createDb() {
    const books: Book[] = [
      { id: 1, title: "Moby Dick", author: "Herman Melville", publisher: "Almadraba", edition: "Special", summary: "Moby-Dick; or, The Whale is a novel by Herman Melville, first published in 1851. It is considered to be one of the Great American Novels and a treasure of world literature. The story tells the adventures of wandering sailor Ishmael, and his voyage on the whaleship Pequod, commanded by Captain Ahab. Ishmael soon learns that Ahab has one purpose on this voyage: to seek out Moby Dick, a ferocious, enigmatic white sperm whale. In a previous encounter, the whale destroyed Ahab's boat and bit off his leg, which now drives Ahab to take revenge." },
      { id: 2, title: "Software Architecture in Practice", author: "Bass, Clements, Kazman", publisher: "Addison Wesley", edition: "Third", summary: "The award-winning and highly influential Software Architecture in Practice, Third Edition, has been substantially revised to reflect the latest developments in the field. In a real-world setting, the book once again introduces the concepts and best practices of software architecture―how a software system is structured and how that system’s elements are meant to interact. Distinct from the details of implementation, algorithm, and data representation, an architecture holds the key to achieving system" },
      { id: 3, title: "Harry Potter and The Philosopher'S Stone", author: "J. K. Rowling", publisher: "Bloomsbury Plc", edition: "English edition", summary: "Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment with a purple seal, they are swiftly confiscated by his grisly aunt and uncle. Then, on Harry's eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news: Harry Potter is a wizard, and he has a place at Hogwarts School of Witchcraft and Wizardry. An incredible adventure is about to begin!" },
      { id: 4, title: "Harry Potter And The Chamber Of Secrets", author: "J. K. Rowling", publisher: "Bloomsbury Plc", edition: "English edition", summary: "Harry Potter's summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors - and then the attacks start. Students are found as though turned to stone . Dobby's sinister predictions seem to be coming true." },
      { id: 5, title: "Reina roja", author: "Juan Gomez-Jurado", publisher: "Ediciones B", edition: "First", summary: "Antonia Scott es especial. Muy especial. No es policía ni criminalista. Nunca ha empuñado un arma ni llevado una placa, y, sin embargo, ha resuelto decenas de crímenes." },
      { id: 6, title: "The Shadow Of The Wind: The Cemetery of Forgotten Books 1", author: "Carlos Ruiz Zafon", publisher: "Planeta", edition: "English", summary: "Hidden in the heart of the old city of Barcelona is the 'Cemetery of Lost Books', a labyrinthine library of obscure and forgotten titles that have long gone out of print. To this library, a man brings his 10-year-old son Daniel one cold morning in 1945. Daniel is allowed to choose one book from the shelves and pulls out 'The Shadow of the Wind' by Julian Carax." },
      { id: 7, title: "La celestina", author: "Fernando de Rojas", publisher: "Planeta", edition: "English", summary: "In 1499, an anonymous 16-act play was published in the Spanish town of Burgos that influenced the flourishing of the Spanish language and literature. Known as the La Comedia of Calisto and Melibea, it became widely popular. As a result, other editions were published in the next three years. A second edition came off the press in 1500, and a third edition was printed in 1502. In this 1502 edition, readers could put a name to the author—Fernando de Rojas—who added five more acts with an introduction and concluding material. The title was then changed to the La Tragicomedia de Calisto y Melibea, but this masterpiece later became known simply as La Celestina—the name of the cunning and seducing protagonist. Calisto, a young nobleman, sees Melibea and falls head-over-heels in love. However, Melibea rejects him. Calisto enlists Celestina, an old woman who has seen and done it all, to help him win over the fair young lady. Celestina is successful, but the costs are high. By the end there has been a murder, a suicide, a more-or-less accidental death, and two characters have been beheaded for their actions." }
    ];
    return { books };
  }
}
